### PR TITLE
Menu setup

### PR DESCRIPTION
**Pull request by zifeo**

### CODE REVIEW

**Comment by timozattol** [comment]
I prefer to keep "parent" instead of  "p", even though we use it so much. We should refactor that back for clarity

**Comment by timozattol** [comment]
WOA disco time :tada: 

The game is flashing hard, something is wrong

**Comment by timozattol** [comment]
Really cool menus btw! :+1:

**Comment by zifeo** [comment]
To be tested, everything should be solved.

**Comment by zifeo** [comment]
Tests works !

**Pull request closed without merging**
